version: 1.0.{build}
image: Visual Studio 2017
before_build:
- cmd: dotnet restore
build:
  verbosity: minimal
artifacts:
- path: '**\*.nupkg'
  name: Messaia.Net.PostgreSQL.BulkExtensions
deploy:
- provider: NuGet
  api_key:
    secure: eJdVIoJ3pqLwr4ae7EwrYlMVNqOwIER8rliesjv1QWEX+CXqOlyyB9v+/dvesDpN
  artifact: /.*\.nupkg/